# Generated by Django 4.2.10 on 2024-02-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('phone_number', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, choices=[('r', 'Regular'), ('a', 'Admin')], default='r', help_text='Role of this team member', max_length=1)),
            ],
        ),
    ]
