# Generated by Django 4.2.10 on 2024-02-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='status',
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(blank=True, choices=[('regular', 'Regular'), ('admin', 'Admin')], default='regular', help_text='Role of this team member', max_length=20),
        ),
    ]
